### ISSUE TITLE
Waiting process

### ISSUE THREAD

**Issue by Alejandroprada** [Ghirensics/ghiro#3] opened 2015-04-13 10:50 UTC
Hi guys,

I'm having some troubles testing ghiro on my laptop. This is weird, because I've also tested on my desktop computer and it works fine.

The problem is when I open a new case. After uploading some pics, the process changes to the waiting state and it doesn't change its state anymore. I go to the "images" tab, but it shows "No data available in table".

I'm running ghiro 0.2-1 OVA version in both computers.

Does anyone know what's the problem?

Thanks in advance,

Alex.

**Comment by mjoshy** [comment] 2015-04-17 05:38
Hello Alex,
I think you forgot to execute "python manage.py process" after executing "python manage.py runserver".
The process script makes the whole magic happen.

**Comment by jekil** [comment] 2015-04-26 20:38
@Alejandroprada are you analyzing the same set of images in both workstations?
Did you run any command inside the appliance? (it should work out of the box)

**Comment by jekil** [comment] 2015-07-25 13:42
I am closing this because requested feedback is missing and we are unable to reproduce the issue. Feel free to reopen this ticket with the information needed.

**Closed by jekil** 2015-07-25 13:42 UTC
Labels: Feedback
